### ISSUE TITLE
dlcenc.py for resign DLC files (0 file)?

### ISSUE THREAD

**Issue by ghost** [schdub/dlcsync#4]
Is this Script (dlcenc.py) for signing the 0 file after modifieng the xmls in 1 file?
I'm searching for a working script, which creates the 0-file (zero-file) from the modifief XML--Files in the 1-file.

thanks a lot

**Comment by nathan666** [comment]
Nein dieses script läd den kompletten dlc herunter und entpackt ihn.
So viel ich weiß hat damarist ein Python Script zum erstellen der 0 File  geschrieben.

**Comment by opa114** [comment]
Danke für die Aufklärung. Habe ich mir fast gedacht. Wie kann ich damarist erreichen bzw. wird er das Script teilen?

**Comment by nathan666** [comment]
Ich schreibe ihn über email meistens an.
info(at)damarist.de oder über Facebook, glaube DanielOliver oder so.

**Comment by opa114** [comment]
danke ich schrieb ihn mal an
